apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service
  namespace: default
spec:
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 80
  selectore:
    app: nginx
  type: NodePort
